name = "Vulta"
uuid = "a1e5f1e4-968f-11ea-2041-0d1a008fd0d2"
author = ["Emmett Boudreau <http://emmettboudreau.com/>"]
version = "0.0.1"

[deps]
VulkanCore = "16167f82-ea26-5cba-b1de-ed6fd5e30a11"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
[compat]
julia = "1.3.0"

